### ISSUE TITLE
Tidak perlu try-catch

### ISSUE THREAD

**Issue by yohangdev** [rachadiannovansyah/bootcamp-jds-laravel#1]
https://github.com/rachadiannovansyah/bootcamp-jds-laravel/blob/5b952685750437a2bd0f940b5c05840e04b84230/app/Http/Controllers/AuthorController.php#L85

Sebaiknya tidak perlu pakai try-catch 😁

**Comment by rachadiannovansyah** [comment]
Baru buka lagi repo ini, ternyata ada koreksi maaf mas notifnya tenggelem :smile: 

sudah diperbaiki mas @yohang88 :+1: :grin:
