### ISSUE TITLE
Gunakan `validated()` untuk mendapatkan data yang diinput/request

### ISSUE THREAD

**Issue by yohangdev** [rachadiannovansyah/bootcamp-jds-laravel#2]
https://github.com/rachadiannovansyah/bootcamp-jds-laravel/blob/5b952685750437a2bd0f940b5c05840e04b84230/app/Http/Controllers/CategoryController.php#L47

Mulai kurangi penggunaan `$request->all()`, make sure ganti pakai `$request->validated()` agar hanya data-data yang tervalidasi saja yang boleh disimpan 😁 

Tolong direfactor di kode-kode lainnya juga yes.

**Comment by rachadiannovansyah** [comment]
Done mas @yohang88 :grin:
